// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDIXAG9ted2nU4e_KgSti2ajmxlLp3-aE',
    appId: '1:546119961072:web:7b2629a6b13942b1d9b535',
    messagingSenderId: '546119961072',
    projectId: 'wings-dating-951ed',
    authDomain: 'wings-dating-951ed.firebaseapp.com',
    storageBucket: 'wings-dating-951ed.appspot.com',
    measurementId: 'G-9GGB2052VJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcHVq9mSbSRUWDHe_jmSVafTr_BvXSfkE',
    appId: '1:546119961072:android:ccd2092af11903ccd9b535',
    messagingSenderId: '546119961072',
    projectId: 'wings-dating-951ed',
    storageBucket: 'wings-dating-951ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUM6PqbnYqoNGngQ3TfvFG3udHqAKbypc',
    appId: '1:546119961072:ios:ef020db2491cf562d9b535',
    messagingSenderId: '546119961072',
    projectId: 'wings-dating-951ed',
    storageBucket: 'wings-dating-951ed.appspot.com',
    androidClientId: '546119961072-tmgd1vdoobl00opni9252urkjgmbu4ku.apps.googleusercontent.com',
    iosClientId: '546119961072-ub3rclq1ocqd5v2eikflmb13j97rg27u.apps.googleusercontent.com',
    iosBundleId: 'com.example.wingsDatingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUM6PqbnYqoNGngQ3TfvFG3udHqAKbypc',
    appId: '1:546119961072:ios:ef020db2491cf562d9b535',
    messagingSenderId: '546119961072',
    projectId: 'wings-dating-951ed',
    storageBucket: 'wings-dating-951ed.appspot.com',
    androidClientId: '546119961072-tmgd1vdoobl00opni9252urkjgmbu4ku.apps.googleusercontent.com',
    iosClientId: '546119961072-ub3rclq1ocqd5v2eikflmb13j97rg27u.apps.googleusercontent.com',
    iosBundleId: 'com.example.wingsDatingApp',
  );
}
